# fly.toml app configuration file generated for i-am-the-fold on 2025-10-10T15:05:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'i-am-the-fold'
primary_region = 'lhr'

[deploy]
  release_command = 'dist/server.mjs --check-config'
  release_command_timeout = '30s'

[env]
    POSTHOG_KEY = "phc_x8IOq3sl7lty4xiL1Wbm7SqaH0bvAlZ5ZE48TT3muF7"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 50
    hard_limit = 100

  [[http_service.checks]]
    interval = '30s'
    timeout = '3s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
