# fly.toml app configuration file generated for i-am-the-fold on 2025-10-10T15:05:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'i-am-the-fold'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
